FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend.py readme.md ./
COPY templates/ templates/
# note: must use 2 lines!! else will coppy "templates/" not good.

EXPOSE 5000

ENTRYPOINT [ "python", "backend.py" ]